# Generated by Django 5.2.8 on 2025-12-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_original_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
