# Generated by Django 5.2.8 on 2025-12-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialog',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
