# Generated by Django 5.2.8 on 2026-01-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_pinned_message_pinned_at'),
        ('posts', '0004_post_repost_text_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_post', to='posts.post'),
        ),
    ]
