# Generated by Django 5.2.8 on 2026-02-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_dialoguser_alter_dialog_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='users',
        ),
    ]
