# Generated by Django 5.2.8 on 2026-02-11 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_dialog_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='users',
            field=models.ManyToManyField(related_name='dialogs', through='chat.DialogUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
